# Generated by Django 3.0.8 on 2020-07-27 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wadachi_app', '0003_auto_20200727_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='bridge',
            name='context',
            field=models.TextField(default='デフォルトの値！！'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bridge',
            name='goal',
            field=models.TextField(default='デフォルトのゴール！！'),
            preserve_default=False,
        ),
    ]
